version: "3"
services:

  alice:
    build: .
    volumes:
      - ./build/nodes/PartyA/node.conf:/app/node.conf # The node configuration
      - ./build/nodes/PartyA/network-parameters:/app/network-parameters
      - ./build/nodes/PartyA/additional-node-infos:/app/additional-node-infos

      # The business network participant configuration stating which operator is permitted
      # - ./shared/membership-service-member.conf:/app/cordapps/config/membership-service.conf

      - ./build/nodes/PartyA/cordapps:/app/cordapps
      - ./build/nodes/PartyA/certificates:/app/certificates
      - ./build/nodes/PartyA/logs:/app/logs
    ports:
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
  bob:
    build: .
    volumes:

      - ./build/nodes/PartyB/node.conf:/app/node.conf # The node configuration
      - ./build/nodes/PartyB/network-parameters:/app/network-parameters
      - ./build/nodes/PartyB/additional-node-infos:/app/additional-node-infos

      # The business network participant configuration stating which operator is permitted
      # - ./shared/membership-service-member.conf:/app/cordapps/config/membership-service.conf

      - ./build/nodes/PartyB/cordapps:/app/cordapps
      - ./build/nodes/PartyB/certificates:/app/certificates
      - ./build/nodes/PartyB/logs:/app/logs

    ports:
      - "20001:20001"
      - "20002:20002"
      - "20003:20003"
      - "20004:20004"


  notary:
    build: .
    volumes:
      # The logs to expose to the host machine
      - ./build/nodes/Notary/node.conf:/app/node.conf # The node configuration
      - ./build/nodes/Notary/network-parameters:/app/network-parameters
      - ./build/nodes/Notary/additional-node-infos:/app/additional-node-infos
      - ./build/nodes/Notary/certificates:/app/certificates
      # - ./build/nodes/Notary/cordapps:/app/cordapps
      - ./build/nodes/Notary/logs:/app/logs

    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"

  # charly:
    # build: .
    # volumes:
      # # The node configuration
      # - ./participants/charly/node.conf:/app/node.conf
      # # The network parameters (https://docs.corda.net/network-map.html#network-parameters) all nodes share
      # - ./shared/network-parameters:/app/network-parameters
      # # The additional node infos (https://docs.corda.net/network-map.html#the-additional-node-infos-directory)
      # - ./shared/infos:/app/additional-node-infos
      # # The business network CorDapps
      # - ./shared/cordapps/membership-service-1.0.jar:/app/cordapps/membership-service-1.0.jar
      # - ./shared/cordapps/membership-service-contracts-and-states-1.0.jar:/app/cordapps/membership-service-contracts-and-states-1.0.jar
      # # The business network participant configuration stating which operator is permitted
      # - ./shared/membership-service-bno.conf:/app/cordapps/config/membership-service.conf
      # # The nodes certificate directory containing all three key stores
      # - ./participants/charly/certificates:/app/certificates
      # # The logs to expose to the host machine
      # - ./logs/charly:/app/logs
    # ports:
      # - "40001:40001"
      # - "40002:40002"
      # - "40003:40003"
      # - "40004:40004"
